### ISSUE TITLE
Crash with Upload limit > 0

### ISSUE THREAD

**Issue by kolsys** [YouROK/TorrServer#1]
v1.0.64, OSX

```
Preload: 26d3ebe24ac4848a2bac9889571645672a21ac89 0 / 100.00MB Speed: 0 Peers:[ 5 ] 5 / 52
Create 28 buffers
Preload: 26d3ebe24ac4848a2bac9889571645672a21ac89 1.50MB / 100.00MB Speed: 416.62KB Peers:[ 9 ] 14 / 87
Preload: 26d3ebe24ac4848a2bac9889571645672a21ac89 7.77MB / 100.00MB Speed: 6.47MB Peers:[ 11 ] 15 / 86
Preload: 26d3ebe24ac4848a2bac9889571645672a21ac89 14.31MB / 100.00MB Speed: 5.21MB Peers:[ 12 ] 15 / 87
Preload: 26d3ebe24ac4848a2bac9889571645672a21ac89 22.20MB / 100.00MB Speed: 7.00MB Peers:[ 14 ] 17 / 87
Preload: 26d3ebe24ac4848a2bac9889571645672a21ac89 30.06MB / 100.00MB Speed: 8.59MB Peers:[ 15 ] 18 / 88
panic: upload rate limiter burst size < 16384

goroutine 23867 [running]:
github.com/anacrolix/torrent.(*connection).upload(0xc4200c5080, 0xc437f5d0f0, 0xc43d173c01)
	/home/yourok/Space/Projects/GO/TorrServer/src/github.com/anacrolix/torrent/connection.go:1401 +0x6d1
github.com/anacrolix/torrent.(*connection).fillWriteBuffer(0xc4200c5080, 0xc437f5d0f0)
	/home/yourok/Space/Projects/GO/TorrServer/src/github.com/anacrolix/torrent/connection.go:590 +0x308
github.com/anacrolix/torrent.(*connection).writer(0xc4200c5080, 0xdf8475800)
	/home/yourok/Space/Projects/GO/TorrServer/src/github.com/anacrolix/torrent/connection.go:619 +0x5ad
created by github.com/anacrolix/torrent.(*Client).runHandshookConn
	/home/yourok/Space/Projects/GO/TorrServer/src/github.com/anacrolix/torrent/client.go:805 +0x499
Start web server, version: 1.0.64
Configure client: {
 "CacheSize": 209715200,
 "PreloadBufferSize": 104857600,
 "RetrackersMode": 1,
 "DisableTCP": false,
 "DisableUTP": false,
 "DisableUPNP": false,
 "DisableDHT": false,
 "DisableUpload": false,
 "Encryption": 0,
 "DownloadRateLimit": 0,
 "UploadRateLimit": 1024,
 "ConnectionsLimit": 100
}
```

**Comment by kolsys** [comment]
В 1.0.65 всё ок.
