### ISSUE TITLE
Очередной exception.

### ISSUE THREAD

**Issue by T-Troll** [YouROK/TorrServer#102]
При смене числа пиров с 20 на 25 получил вот такой exception:

```
Client config: {"CacheSize":1073741824,"ReaderReadAHead":90,"PreloadCache":2,"UseDisk":true,"TorrentsSavePath":"/mnt/sda2/torrServer/torrents","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":0,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":300,"ConnectionsLimit":25,"PeersListenPort":0}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x582ee0]
goroutine 77032 [running]:
github.com/anacrolix/torrent.(*Client).lock(...)
        /go/pkg/mod/github.com/anacrolix/torrent@v1.30.3-0.20210816011131-16176b762e4a/client.go:1545
github.com/anacrolix/torrent.(*Client).AddTorrentInfoHashWithStorage(0x0, 0x42560f49, 0x8174ac22, 0xc50d8af7, 0xcefdaf73, 0x5b0c1d1a, 0x0, 0x0, 0x0, 0x1f0b500)
        /go/pkg/mod/github.com/anacrolix/torrent@v1.30.3-0.20210816011131-16176b762e4a/client.go:1139 +0x38
github.com/anacrolix/torrent.(*Client).AddTorrentSpec(0x0, 0x1e6ca00, 0x0, 0x0, 0x2726201, 0x27c118)
        /go/pkg/mod/github.com/anacrolix/torrent@v1.30.3-0.20210816011131-16176b762e4a/client.go:1164 +0x6c
server/torr.NewTorrent(0x1e6ca00, 0x1e030c8, 0x0, 0x0, 0x0)
        /usr/src/torr/server/torr/torrent.go:71 +0x174
server/torr.GetTorrent.func1(0x260c790)
        /usr/src/torr/server/torr/apihelper.go:94 +0x2c
created by server/torr.GetTorrent
        /usr/src/torr/server/torr/apihelper.go:93 +0x124
```

После перезапуска работает нормально.

**Comment by tsynik** [comment]
> При смене числа пиров с 20 на 25 получил вот такой exception

но это не крайний 104-й релиз сервера. В нем добавлена блокировка при изменении настроек для избежания экспшенов, что вызвало некоторы другие проблемы, поэтому это откатили в мастере
