### ISSUE TITLE
Randomly crash with error 'panic: io.Copy will get stuck'

### ISSUE THREAD

**Issue by ixvick** [YouROK/TorrServer#273]
```
2023/06/25 23:00:31 New torrent 59d04246209c1bee075e34433cdbf7bee739f132
2023/06/25 23:00:31 Create cache for: XXXXXXXXXXXXXXXXX.mkv 59d04246209c1bee075e34433cdbf7bee739f132
panic: io.Copy will get stuck

goroutine 650195 [running]:
github.com/anacrolix/torrent/storage.Piece.ReadAt({{0x1151c00?, 0xc00119b950?}, {0xc0004ee880?, 0xc000cf18b0?}}, {0xc0034de000, 0x8000, 0x8000}, 0x4000)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/storage/wrappers.go:89 +0x375
io.(*SectionReader).Read(0xc0009e3890, {0xc0034de000?, 0x2?, 0xc002297cf0?})
	/usr/local/go/src/io/io.go:513 +0x54
io.(*LimitedReader).Read(0xc002e15d10, {0xc0034de000?, 0x4000?, 0x8000?})
	/usr/local/go/src/io/io.go:477 +0x45
io.copyBuffer({0x1149100, 0xc002e15cf8}, {0x1149040, 0xc002e15d10}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:427 +0x1b2
io.Copy(...)
	/usr/local/go/src/io/io.go:386
io.CopyN({0x1149100, 0xc002e15cf8}, {0x11490a0?, 0xc0009e3890}, 0x200000)
	/usr/local/go/src/io/io.go:362 +0x9a
github.com/anacrolix/torrent/storage.Piece.WriteTo({{0x1151c00, 0xc00119b950}, {0xc0004ee880, 0xf94}}, {0x1149100, 0xc002e15cf8})
	/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/storage/wrappers.go:51 +0x186
github.com/anacrolix/torrent.(*Torrent).hashPiece(0xc0004fd500, 0xf94)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/torrent.go:1035 +0x4fa
github.com/anacrolix/torrent.(*Torrent).pieceHasher(0xc0004fd500, 0xf94)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/torrent.go:2315 +0x75
created by github.com/anacrolix/torrent.(*Torrent).tryCreatePieceHasher
	/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/torrent.go:2274 +0x12b
```

/usr/bin/torrserver --version
TorrServer MatriX.124

file /usr/bin/torrserver
/usr/bin/torrserver: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, no section header

**Comment by tsynik** [comment]
> /usr/bin/torrserver --version TorrServer MatriX.124
> 
> file /usr/bin/torrserver /usr/bin/torrserver: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, no section header

Looks like you're using disk cache and your media not accessible somehow. Use RAM cache and there will be no such errors. Here is nothing to do with torrserver, it's probably media / torrent library issue.
