### ISSUE TITLE
[BUG] Стал часто падать при добавлении торрента через magnet

### ISSUE THREAD

**Issue by visilya** [YouROK/TorrServer#468]
**Describe the bug**
Поиск фильма в jacket (red) и добавление оттуда по клику приводит к `panic: runtime error`. Так же пробовал копировать magnet ссылку и добавить вручную - одинаковое падение.

**To Reproduce**
1. Открыть torrserver
2. Добавить торрент `magnet:?xt=urn:btih:8694e3f29134b26640498316a7cb0b0e620f856e`
3. See error

**Expected behavior**
Торрент добавился и доступен.

**Screenshots**
![image](https://github.com/user-attachments/assets/24b0bcea-8d4e-4a73-93c8-d18e557d2abf)

**Desktop (please complete the following information):**
 - OS: Debian + docker [build from this](https://github.com/MrKsey/torrserver-plus/blob/main/Dockerfile)
 - TorrServer Version MatriX.134

**Additional context**
<details><summary>Some logs</summary>

```
=========== START ===========
TorrServer MatriX.134, go1.23.2, CPU Num: 8
DNS resolver OK
2024/11/09 09:25:35 UTC0 XPathDBRouter: Registered new DB "JsonDB", total 1 DBs registered
2024/11/09 09:25:35 UTC0 XPathDBRouter: Registered new route "" for DB "JsonDB", total 1 routes
2024/11/09 09:25:35 UTC0 XPathDBRouter: Registered new route "settings" for DB "JsonDB", total 2 routes
2024/11/09 09:25:35 UTC0 XPathDBRouter: Registered new route "viewed" for DB "JsonDB", total 3 routes
2024/11/09 09:25:35 UTC0 XPathDBRouter: Registered new DB "TDB", total 2 DBs registered
2024/11/09 09:25:35 UTC0 XPathDBRouter: Registered new route "torrents" for DB "TDB", total 4 routes
2024/11/09 09:25:35 UTC0 Check web port 8090
2024/11/09 09:25:35 UTC0 Start TorrServer MatriX.134 torrent v1.2.22
2024/11/09 09:25:35 UTC0 Local IPs: [172.24.0.8]
2024/11/09 09:25:35 UTC0 Open peers listen port: 63802
2024/11/09 09:25:35 UTC0 Client config: {"CacheSize":104857600,"ReaderReadAHead":90,"PreloadCache":32,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":true,"ForceEncrypt":true,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":true,"RutorSearchAddr":"","EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":500,"PeersListenPort":0,"SslPort":0,"SslCert":"","SslKey":"","ResponsiveMode":true}
2024/11/09 09:25:39 UTC0 PublicIp4: 128.0.128.109
2024/11/09 09:25:39 UTC0 Update rutor db
2024/11/09 09:25:39 UTC0 Less 3 hours rutor db old
2024/11/09 09:25:39 UTC0 Load rutor db
2024/11/09 09:25:39 UTC0 Start http server at port 8090
2024/11/09 09:25:41 UTC0 Index rutor db
2024/11/09 09:25:42 UTC0 Torrents count: 179412
2024/11/09 09:25:42 UTC0 Indexed words: 67965
[2024-11-09 09:26:32 +0000 NIL github.com/anacrolix/torrent client.go:321]
  dht server on 0.0.0.0:63802 (node id 41ac86bbad99b92c2198ac9bbc3d8eb71e3d03c9) completed bootstrap ({40 24})
2024/11/09 09:26:46 UTC0 add torrent magnet:?xt=urn:btih:8694e3f29134b26640498316a7cb0b0e620f856e
Trackers file done
2024/11/09 09:26:51 UTC0 Create cache for: Ajta.2022.WEB-DL.2160p.SDR.mkv 8694e3f29134b26640498316a7cb0b0e620f856e
2024/11/09 09:26:51 UTC0 Movie:  true
2024/11/09 09:26:51 UTC0 YEAR: 2022
2024/11/09 09:26:51 UTC0 Ajta
api key is empty
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbf8b16]
goroutine 380 [running]:
github.com/cyruzin/golang-tmdb.(*Client).GetSearchMulti(0x0, {0xc01145a440, 0x4}, 0x8?)
	github.com/cyruzin/golang-tmdb@v1.6.7/search.go:154 +0xd6
server/poster.getUtil({0xc01145a440, 0x4}, 0x0, 0x1, 0x7e6)
	server/poster/poster.go:125 +0x1f6
server/poster.GetPoster({0xc01145a400?, 0x0?})
	server/poster/poster.go:304 +0xac9
server/web/api.addTorrent.func1()
	server/web/api/torrents.go:132 +0x18f
created by server/web/api.addTorrent in goroutine 267
	server/web/api/torrents.go:114 +0x618
```
</details>

**Comment by tsynik** [comment]
в упор не вижу server/poster/poster.go из-за которого возникает искючение
