### ISSUE TITLE
Периодические вылеты Matrix.102 на Armv7

### ISSUE THREAD

**Issue by T-Troll** [YouROK/TorrServer#88]
Рандомно (обычно под нагрузкой, часто после подключения нового клиента) вылетает с такой диагностикой:

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x584588]

goroutine 10717 [running]:
github.com/anacrolix/torrent.(*Client).lock(...)
        /go/pkg/mod/github.com/anacrolix/torrent@v1.29.1/client.go:1543
github.com/anacrolix/torrent.(*Client).AddTorrentInfoHashWithStorage(0x0, 0x8afcf974, 0xde5dcd34, 0xd4fc8189, 0x55ec0f8e, 0x50c2f879, 0x0, 0x0, 0x0, 0x26b5800)
        /go/pkg/mod/github.com/anacrolix/torrent@v1.29.1/client.go:1141 +0x38
github.com/anacrolix/torrent.(*Client).AddTorrentSpec(0x0, 0x27b2c00, 0x0, 0x7ff, 0x1, 0x105bc0)
        /go/pkg/mod/github.com/anacrolix/torrent@v1.29.1/client.go:1166 +0x6c
server/torr.NewTorrent(0x27b2c00, 0x2603140, 0x0, 0x0, 0x0)
        /usr/src/torr/server/torr/torrent.go:71 +0x174
server/torr.GetTorrent.func1(0x2ac16b0)
        /usr/src/torr/server/torr/apihelper.go:94 +0x2c
created by server/torr.GetTorrent
        /usr/src/torr/server/torr/apihelper.go:93 +0x124
```

**Comment by tsynik** [comment]
> Рандомно (обычно под нагрузкой, часто после подключения нового клиента) вылетает

проверь поведение в MatriX.103

**Comment by T-Troll** [comment]
Спасибо.
Smoke test прошел, погоняю пару дней и закрою этот таск, если не будет падать.

**Comment by T-Troll** [comment]
Пока не вылетает, закрываю баг.
